### ISSUE TITLE
add watsonx-admin-api-key to secret manager

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-rag-sample-da#59]

**Comment by ocofaigh** [comment]
Spoke with Vincent on this. The issue was to tracking taking the watson apikey that was passed and adding it to a secrets manager secret in the DA code. However it seems that logic has already been added: https://github.com/terraform-ibm-modules/terraform-ibm-rag-sample-da/blob/587dfec89ec1715cae3cda1e314580a7861099df/solutions/banking/main.tf#L75-L90

Closing this issue
